dado = input('Digite algo: ')
print(type(dado))
print(f'{dado} é alfabético? {dado.isalpha()}')
print(f'{dado} é numérico? {dado.isnumeric()}')
print(f'{dado} é alfanumérico? {dado.isalnum()}')
print(f'{dado} é ASCII? {dado.isascii()}')
print(f'{dado} é um dígito? {dado.isdigit()}')
print(f'{dado} é decimal? {dado.isdecimal()}')
print(f'{dado} é um identificador? {dado.isidentifier()}')
print(f'{dado} está todo em minúsculo? {dado.islower()}')
print(f'{dado} está todo em maiúsculo? {dado.isupper()}')
print(f'{dado} é imprimível? {dado.isprintable()}')
print(f'{dado} é um espaço? {dado.isspace()}')
print(f'{dado} é um título? {dado.istitle()}')
