/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ftec;

import java.util.random.RandomGenerator;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class TelaJogo extends javax.swing.JFrame {
    int sorteado;
    int contJogadas = 10;
    boolean jogoAtivo;
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        RandomGenerator gerador = RandomGenerator.getDefault();
        sorteado = gerador.nextInt(1, 101);
        jogoAtivo = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRecomecar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        btnArriscar = new javax.swing.JButton();
        lblDica = new javax.swing.JLabel();
        lblTentativas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Número:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Dica:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Número de Tentativas Restantes:");

        btnRecomecar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRecomecar.setText("Recomeçar");
        btnRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomecarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        txtNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnArriscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnArriscar.setText("Arriscar");
        btnArriscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriscarActionPerformed(evt);
            }
        });

        lblDica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTentativas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTentativas.setForeground(new java.awt.Color(255, 0, 51));
        lblTentativas.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTentativas))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(lblDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(btnRecomecar)))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnFechar)
                                .addComponent(btnArriscar)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArriscar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTentativas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecomecar)
                    .addComponent(btnFechar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        dispose();
    }                                         

    private void btnArriscarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String resultado = "";
        
        if(jogoAtivo == true) {
            contJogadas--;
            if(contJogadas == 0) {
                jogoAtivo = false;
                JOptionPane.showMessageDialog(null, "Não há mais jogadas restantes!\nO número sorteado foi " + sorteado, "Fim de Jogo!", JOptionPane.ERROR_MESSAGE);
                
            }
            lblTentativas.setText(Integer.toString(contJogadas));
            int palpite = Integer.parseInt(txtNum.getText());
            if(palpite == sorteado) {
                resultado += "\nVocê ACERTOU!!!";
                jogoAtivo = false;
                JOptionPane.showMessageDialog(null, resultado + "\nO número sorteado foi " + sorteado, "Fim de Jogo!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                resultado += "\nVocê errou!";
                if(palpite < sorteado) {
                    lblDica.setText("O número sorteado é maior");
                } else {
                    lblDica.setText("O número sorteado é menor");
                }
            }
        } 
       
    }                                           

    private void btnRecomecarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        lblTentativas.setText(Integer.toString(10));
        txtNum.setText("");
        RandomGenerator gerador = RandomGenerator.getDefault();
        sorteado = gerador.nextInt(1, 101);
        jogoAtivo = true;
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnArriscar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRecomecar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblTentativas;
    private javax.swing.JTextField txtNum;
    // End of variables declaration                   
}
